// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsCryptoProApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsCryptoProApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsCryptoProApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashCryptoProApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashCryptoProApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashCryptoProApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum CAdESFormat: Int {
  case bES = 0
  case xLongType1 = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct CryptoProLicenseInfo: Hashable {
  var serialNumber: String? = nil
  var expiredThroughDays: Int64? = nil
  var licenseInstallDate: String? = nil
  var existingLicenseStatus: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CryptoProLicenseInfo? {
    let serialNumber: String? = nilOrValue(pigeonVar_list[0])
    let expiredThroughDays: Int64? = nilOrValue(pigeonVar_list[1])
    let licenseInstallDate: String? = nilOrValue(pigeonVar_list[2])
    let existingLicenseStatus: Int64? = nilOrValue(pigeonVar_list[3])

    return CryptoProLicenseInfo(
      serialNumber: serialNumber,
      expiredThroughDays: expiredThroughDays,
      licenseInstallDate: licenseInstallDate,
      existingLicenseStatus: existingLicenseStatus
    )
  }
  func toList() -> [Any?] {
    return [
      serialNumber,
      expiredThroughDays,
      licenseInstallDate,
      existingLicenseStatus,
    ]
  }
  static func == (lhs: CryptoProLicenseInfo, rhs: CryptoProLicenseInfo) -> Bool {
    return deepEqualsCryptoProApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCryptoProApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Certificate: Hashable {
  var alias: String? = nil
  var owner: String? = nil
  var issuer: String? = nil
  var serialNumber: String? = nil
  var algorithm: String? = nil
  var version: Int64? = nil
  var oid: String? = nil
  var validFrom: String? = nil
  var validTo: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Certificate? {
    let alias: String? = nilOrValue(pigeonVar_list[0])
    let owner: String? = nilOrValue(pigeonVar_list[1])
    let issuer: String? = nilOrValue(pigeonVar_list[2])
    let serialNumber: String? = nilOrValue(pigeonVar_list[3])
    let algorithm: String? = nilOrValue(pigeonVar_list[4])
    let version: Int64? = nilOrValue(pigeonVar_list[5])
    let oid: String? = nilOrValue(pigeonVar_list[6])
    let validFrom: String? = nilOrValue(pigeonVar_list[7])
    let validTo: String? = nilOrValue(pigeonVar_list[8])

    return Certificate(
      alias: alias,
      owner: owner,
      issuer: issuer,
      serialNumber: serialNumber,
      algorithm: algorithm,
      version: version,
      oid: oid,
      validFrom: validFrom,
      validTo: validTo
    )
  }
  func toList() -> [Any?] {
    return [
      alias,
      owner,
      issuer,
      serialNumber,
      algorithm,
      version,
      oid,
      validFrom,
      validTo,
    ]
  }
  static func == (lhs: Certificate, rhs: Certificate) -> Bool {
    return deepEqualsCryptoProApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCryptoProApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SuccessSign: Hashable {
  var base64: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SuccessSign? {
    let base64 = pigeonVar_list[0] as! String

    return SuccessSign(
      base64: base64
    )
  }
  func toList() -> [Any?] {
    return [
      base64
    ]
  }
  static func == (lhs: SuccessSign, rhs: SuccessSign) -> Bool {
    return deepEqualsCryptoProApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCryptoProApi(value: toList(), hasher: &hasher)
  }
}

private class CryptoProApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CAdESFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return CryptoProLicenseInfo.fromList(self.readValue() as! [Any?])
    case 131:
      return Certificate.fromList(self.readValue() as! [Any?])
    case 132:
      return SuccessSign.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CryptoProApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CAdESFormat {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CryptoProLicenseInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? Certificate {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? SuccessSign {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CryptoProApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CryptoProApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CryptoProApiPigeonCodecWriter(data: data)
  }
}

class CryptoProApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CryptoProApiPigeonCodec(readerWriter: CryptoProApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CryptoProFlutterApi {
  func initCSP() throws -> Bool
  func getLicense() throws -> CryptoProLicenseInfo?
  func setLicense(number: String) throws -> Bool
  func importPFXContainer(filePath: String, password: String, newPassword: String?, completion: @escaping (Result<[Certificate], Error>) -> Void)
  func importContainerFromExternalStorage(storageName: String, password: String, newPassword: String?, completion: @escaping (Result<[Certificate], Error>) -> Void)
  func getCertificateWithPrivateKeyFromPersonalContainer(certificateAlias: String, password: String, completion: @escaping (Result<Certificate, Error>) -> Void)
  func readContainerFromExternalStorage(storageName: String, password: String, completion: @escaping (Result<[Certificate], Error>) -> Void)
  func addCertificatesToTrustedStorage(paths: [String], completion: @escaping (Result<Void, Error>) -> Void)
  func deleteCertificateWithPKeyFromPersonalStorage(certificateAlias: String, completion: @escaping (Result<Void, Error>) -> Void)
  func getInstalledCertificatesWithPrivateKeys(completion: @escaping (Result<[Certificate], Error>) -> Void)
  func signFile(filePath: String, certificateAlias: String, password: String, format: CAdESFormat, signHash: Bool, isDetached: Bool, disableOnlineValidation: Bool, tsaUrl: String?, storageName: String?, completion: @escaping (Result<SuccessSign, Error>) -> Void)
  func signMessage(message: String, certificateAlias: String, password: String, format: CAdESFormat, isDetached: Bool, signHash: Bool, disableOnlineValidation: Bool, tsaUrl: String?, storageName: String?, completion: @escaping (Result<SuccessSign, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CryptoProFlutterApiSetup {
  static var codec: FlutterStandardMessageCodec { CryptoProApiPigeonCodec.shared }
  /// Sets up an instance of `CryptoProFlutterApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CryptoProFlutterApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initCSPChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.initCSP\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initCSPChannel.setMessageHandler { _, reply in
        do {
          let result = try api.initCSP()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initCSPChannel.setMessageHandler(nil)
    }
    let getLicenseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.getLicense\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLicenseChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getLicense()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLicenseChannel.setMessageHandler(nil)
    }
    let setLicenseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.setLicense\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLicenseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let numberArg = args[0] as! String
        do {
          let result = try api.setLicense(number: numberArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLicenseChannel.setMessageHandler(nil)
    }
    let importPFXContainerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.importPFXContainer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      importPFXContainerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let passwordArg = args[1] as! String
        let newPasswordArg: String? = nilOrValue(args[2])
        api.importPFXContainer(filePath: filePathArg, password: passwordArg, newPassword: newPasswordArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      importPFXContainerChannel.setMessageHandler(nil)
    }
    let importContainerFromExternalStorageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.importContainerFromExternalStorage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      importContainerFromExternalStorageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let storageNameArg = args[0] as! String
        let passwordArg = args[1] as! String
        let newPasswordArg: String? = nilOrValue(args[2])
        api.importContainerFromExternalStorage(storageName: storageNameArg, password: passwordArg, newPassword: newPasswordArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      importContainerFromExternalStorageChannel.setMessageHandler(nil)
    }
    let getCertificateWithPrivateKeyFromPersonalContainerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.getCertificateWithPrivateKeyFromPersonalContainer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCertificateWithPrivateKeyFromPersonalContainerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let certificateAliasArg = args[0] as! String
        let passwordArg = args[1] as! String
        api.getCertificateWithPrivateKeyFromPersonalContainer(certificateAlias: certificateAliasArg, password: passwordArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCertificateWithPrivateKeyFromPersonalContainerChannel.setMessageHandler(nil)
    }
    let readContainerFromExternalStorageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.readContainerFromExternalStorage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readContainerFromExternalStorageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let storageNameArg = args[0] as! String
        let passwordArg = args[1] as! String
        api.readContainerFromExternalStorage(storageName: storageNameArg, password: passwordArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readContainerFromExternalStorageChannel.setMessageHandler(nil)
    }
    let addCertificatesToTrustedStorageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.addCertificatesToTrustedStorage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addCertificatesToTrustedStorageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathsArg = args[0] as! [String]
        api.addCertificatesToTrustedStorage(paths: pathsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addCertificatesToTrustedStorageChannel.setMessageHandler(nil)
    }
    let deleteCertificateWithPKeyFromPersonalStorageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.deleteCertificateWithPKeyFromPersonalStorage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteCertificateWithPKeyFromPersonalStorageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let certificateAliasArg = args[0] as! String
        api.deleteCertificateWithPKeyFromPersonalStorage(certificateAlias: certificateAliasArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteCertificateWithPKeyFromPersonalStorageChannel.setMessageHandler(nil)
    }
    let getInstalledCertificatesWithPrivateKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.getInstalledCertificatesWithPrivateKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getInstalledCertificatesWithPrivateKeysChannel.setMessageHandler { _, reply in
        api.getInstalledCertificatesWithPrivateKeys { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getInstalledCertificatesWithPrivateKeysChannel.setMessageHandler(nil)
    }
    let signFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.signFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let certificateAliasArg = args[1] as! String
        let passwordArg = args[2] as! String
        let formatArg = args[3] as! CAdESFormat
        let signHashArg = args[4] as! Bool
        let isDetachedArg = args[5] as! Bool
        let disableOnlineValidationArg = args[6] as! Bool
        let tsaUrlArg: String? = nilOrValue(args[7])
        let storageNameArg: String? = nilOrValue(args[8])
        api.signFile(filePath: filePathArg, certificateAlias: certificateAliasArg, password: passwordArg, format: formatArg, signHash: signHashArg, isDetached: isDetachedArg, disableOnlineValidation: disableOnlineValidationArg, tsaUrl: tsaUrlArg, storageName: storageNameArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signFileChannel.setMessageHandler(nil)
    }
    let signMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.signMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! String
        let certificateAliasArg = args[1] as! String
        let passwordArg = args[2] as! String
        let formatArg = args[3] as! CAdESFormat
        let isDetachedArg = args[4] as! Bool
        let signHashArg = args[5] as! Bool
        let disableOnlineValidationArg = args[6] as! Bool
        let tsaUrlArg: String? = nilOrValue(args[7])
        let storageNameArg: String? = nilOrValue(args[8])
        api.signMessage(message: messageArg, certificateAlias: certificateAliasArg, password: passwordArg, format: formatArg, isDetached: isDetachedArg, signHash: signHashArg, disableOnlineValidation: disableOnlineValidationArg, tsaUrl: tsaUrlArg, storageName: storageNameArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signMessageChannel.setMessageHandler(nil)
    }
  }
}
