// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CryptoProApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class CAdESFormat(val raw: Int) {
  BES(0),
  XLONG_TYPE1(1);

  companion object {
    fun ofRaw(raw: Int): CAdESFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CryptoProLicenseInfo (
  val serialNumber: String? = null,
  val expiredThroughDays: Long? = null,
  val licenseInstallDate: String? = null,
  val existingLicenseStatus: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CryptoProLicenseInfo {
      val serialNumber = pigeonVar_list[0] as String?
      val expiredThroughDays = pigeonVar_list[1] as Long?
      val licenseInstallDate = pigeonVar_list[2] as String?
      val existingLicenseStatus = pigeonVar_list[3] as Long?
      return CryptoProLicenseInfo(serialNumber, expiredThroughDays, licenseInstallDate, existingLicenseStatus)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      serialNumber,
      expiredThroughDays,
      licenseInstallDate,
      existingLicenseStatus,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CryptoProLicenseInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return CryptoProApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Certificate (
  val alias: String? = null,
  val owner: String? = null,
  val issuer: String? = null,
  val serialNumber: String? = null,
  val algorithm: String? = null,
  val version: Long? = null,
  val oid: String? = null,
  val validFrom: String? = null,
  val validTo: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Certificate {
      val alias = pigeonVar_list[0] as String?
      val owner = pigeonVar_list[1] as String?
      val issuer = pigeonVar_list[2] as String?
      val serialNumber = pigeonVar_list[3] as String?
      val algorithm = pigeonVar_list[4] as String?
      val version = pigeonVar_list[5] as Long?
      val oid = pigeonVar_list[6] as String?
      val validFrom = pigeonVar_list[7] as String?
      val validTo = pigeonVar_list[8] as String?
      return Certificate(alias, owner, issuer, serialNumber, algorithm, version, oid, validFrom, validTo)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alias,
      owner,
      issuer,
      serialNumber,
      algorithm,
      version,
      oid,
      validFrom,
      validTo,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Certificate) {
      return false
    }
    if (this === other) {
      return true
    }
    return CryptoProApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SuccessSign (
  val base64: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SuccessSign {
      val base64 = pigeonVar_list[0] as String
      return SuccessSign(base64)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      base64,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SuccessSign) {
      return false
    }
    if (this === other) {
      return true
    }
    return CryptoProApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class CryptoProApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CAdESFormat.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CryptoProLicenseInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Certificate.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SuccessSign.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CAdESFormat -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is CryptoProLicenseInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is Certificate -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SuccessSign -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CryptoProFlutterApi {
  fun initCSP(): Boolean
  fun getLicense(): CryptoProLicenseInfo?
  fun setLicense(number: String): Boolean
  fun importPFXContainer(filePath: String, password: String, newPassword: String?, callback: (Result<List<Certificate>>) -> Unit)
  fun importContainerFromExternalStorage(storageName: String, password: String, newPassword: String?, callback: (Result<List<Certificate>>) -> Unit)
  fun getCertificateWithPrivateKeyFromPersonalContainer(certificateAlias: String, password: String, callback: (Result<Certificate>) -> Unit)
  fun readContainerFromExternalStorage(storageName: String, password: String, callback: (Result<List<Certificate>>) -> Unit)
  fun addCertificatesToTrustedStorage(paths: List<String>, callback: (Result<Unit>) -> Unit)
  fun deleteCertificateWithPKeyFromPersonalStorage(certificateAlias: String, callback: (Result<Unit>) -> Unit)
  fun getInstalledCertificatesWithPrivateKeys(callback: (Result<List<Certificate>>) -> Unit)
  fun signFile(filePath: String, certificateAlias: String, password: String, format: CAdESFormat, signHash: Boolean, isDetached: Boolean, disableOnlineValidation: Boolean, tsaUrl: String?, storageName: String?, callback: (Result<SuccessSign>) -> Unit)
  fun signMessage(message: String, certificateAlias: String, password: String, format: CAdESFormat, isDetached: Boolean, signHash: Boolean, disableOnlineValidation: Boolean, tsaUrl: String?, storageName: String?, callback: (Result<SuccessSign>) -> Unit)

  companion object {
    /** The codec used by CryptoProFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CryptoProApiPigeonCodec()
    }
    /** Sets up an instance of `CryptoProFlutterApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CryptoProFlutterApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.initCSP$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.initCSP())
            } catch (exception: Throwable) {
              CryptoProApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.getLicense$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getLicense())
            } catch (exception: Throwable) {
              CryptoProApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.setLicense$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val numberArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.setLicense(numberArg))
            } catch (exception: Throwable) {
              CryptoProApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.importPFXContainer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val passwordArg = args[1] as String
            val newPasswordArg = args[2] as String?
            api.importPFXContainer(filePathArg, passwordArg, newPasswordArg) { result: Result<List<Certificate>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CryptoProApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CryptoProApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.importContainerFromExternalStorage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val storageNameArg = args[0] as String
            val passwordArg = args[1] as String
            val newPasswordArg = args[2] as String?
            api.importContainerFromExternalStorage(storageNameArg, passwordArg, newPasswordArg) { result: Result<List<Certificate>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CryptoProApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CryptoProApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.getCertificateWithPrivateKeyFromPersonalContainer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val certificateAliasArg = args[0] as String
            val passwordArg = args[1] as String
            api.getCertificateWithPrivateKeyFromPersonalContainer(certificateAliasArg, passwordArg) { result: Result<Certificate> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CryptoProApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CryptoProApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.readContainerFromExternalStorage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val storageNameArg = args[0] as String
            val passwordArg = args[1] as String
            api.readContainerFromExternalStorage(storageNameArg, passwordArg) { result: Result<List<Certificate>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CryptoProApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CryptoProApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.addCertificatesToTrustedStorage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathsArg = args[0] as List<String>
            api.addCertificatesToTrustedStorage(pathsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CryptoProApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CryptoProApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.deleteCertificateWithPKeyFromPersonalStorage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val certificateAliasArg = args[0] as String
            api.deleteCertificateWithPKeyFromPersonalStorage(certificateAliasArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CryptoProApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CryptoProApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.getInstalledCertificatesWithPrivateKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getInstalledCertificatesWithPrivateKeys{ result: Result<List<Certificate>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CryptoProApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CryptoProApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.signFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val certificateAliasArg = args[1] as String
            val passwordArg = args[2] as String
            val formatArg = args[3] as CAdESFormat
            val signHashArg = args[4] as Boolean
            val isDetachedArg = args[5] as Boolean
            val disableOnlineValidationArg = args[6] as Boolean
            val tsaUrlArg = args[7] as String?
            val storageNameArg = args[8] as String?
            api.signFile(filePathArg, certificateAliasArg, passwordArg, formatArg, signHashArg, isDetachedArg, disableOnlineValidationArg, tsaUrlArg, storageNameArg) { result: Result<SuccessSign> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CryptoProApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CryptoProApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.crypto_pro_flutter.CryptoProFlutterApi.signMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as String
            val certificateAliasArg = args[1] as String
            val passwordArg = args[2] as String
            val formatArg = args[3] as CAdESFormat
            val isDetachedArg = args[4] as Boolean
            val signHashArg = args[5] as Boolean
            val disableOnlineValidationArg = args[6] as Boolean
            val tsaUrlArg = args[7] as String?
            val storageNameArg = args[8] as String?
            api.signMessage(messageArg, certificateAliasArg, passwordArg, formatArg, isDetachedArg, signHashArg, disableOnlineValidationArg, tsaUrlArg, storageNameArg) { result: Result<SuccessSign> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CryptoProApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CryptoProApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
